name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12.16.1"]
        deno: ["0.35.0"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: test in ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Environment
        run: |
          node -v
          npm -v
          yarn --version
          deno --version

      - name: Install
        run: yarn

      - name: Check code format
        run: npm run check

      - name: Lint
        run: npm run lint

      # - name: Test and Coveralls
      #   if: runner.os == 'macOS' && github.event_name != 'pull_request'
      #   env:
      #     COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
      #     COVERALLS_GIT_BRANCH: "${{ github.ref }}"
      #   run: npm run test-coveralls

      - name: Test
        # if: github.event_name == 'pull_request'
        run: npm run test

      - name: Compile
        run: |
          npm run compile

      - name: Package
        run: npm run build

      - uses: actions/upload-artifact@v1
        if: runner.os == 'macOS'
        with:
          name: package
          path: ./vscode_deno.vsix

  release:
    runs-on: ubuntu-latest
    name: "Release to vscode market and github"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: package

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: publish to vscode market
        # require Azure DevOps Personal Access Token
        run: npx vsce publish --packagePath ./package/vscode_deno.vsix --pat ${{ secrets.ADO_TOKEN }}

      - uses: softprops/action-gh-release@v1
        name: publish to Github
        env:
          # require Github Personal Access Token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            ./package/vscode_deno.vsix
          draft: false
